### ISSUE TITLE
if ~/.config/git-credential-pass does not exist test fails

### ISSUE THREAD

**Issue by jaredmontoya** [Xgames123/git-credential-pass#4]
I tried to install an AUR package but it wouldn't install until I ran ```mkdir ~/.config/git-credential-pass```

I think this directory being absent should not prevent installation as people usually don't start configuring programs before they installed them.

It shouldn't be necessary to read through the code to understand that the path mentioned in the failed test is not being resolved because it does not exist yet to just install it.

My reasoning for why it shouldn't be necessary is that when you run the PKGBUILD you expect it to finish without errors, but the PKGBUILD for this app requires you to create a directory without actually explicitly telling that you have to do that.

**Comment by Xgames123** [comment]
Thanks for letting me know.

**Comment by jaredmontoya** [comment]
Thank you for creating a useful program

**Comment by Xgames123** [comment]
Fixed in the latest aur package
